services:
  turing:
    build: 
      context: ./turing
    command: tail -f /dev/null
    volumes:
      - ./turing:/usr/src/app
  jarvis:
    build: 
      context: ./jarvis
    command: tail -f /dev/null
  silver:
    build: 
      context: ./silver
    command: tail -f /dev/null
  # geth:
  #   image: ethereum/client-go
  #   command: --rpc --rpcaddr "
  #   ports:
  #   - "5432:5432"